### ISSUE TITLE
vector

### ISSUE THREAD

**Issue by kimjinho1** [kimjinho1/ft_containers#1]
## description
> **vector를 만들어보자**
## 하면서 알게 되는 내용들
- [x] typename
- [x] explicit
- [x] Allocator
- [x] iterator
- [x] is_integral
- [x] SFINAE(Substitution Failure Is Not An Error) and enable_if 
- [x] iterator_traits
- [x] reverse_iterator
## todo  
- [x] algorithm(equal, lexicographical_compare) 구현  
- [x] is_integral 구현
- [x] enable_if  구현
- [x] iterator_traits  구현
- [x] reverse_iterator 구현
- [x] vector iterator 구현
- [x] vector  구현

**Comment by kimjinho1** [comment]
끝!
